### PR TITLE
Continuous Integration with Release mechanism

### PR DESCRIPTION
**Pull request by dfuchss**
As I had already announced to you, I have now quickly built the CI for the project.
This builds the PDF automatically and makes the current state always available in the GitHub action (there you can find artifacts for each build (namely the PDF)).

If you then want to publish the PDF as a release, you only have to "tag" the corresponding commit in the scheme "vX.Y.Z" (it is important that the tag starts with "v"). 
Then a release will be created automatically and the PDF will be attached as well. 

Feel free to contact me iff anything is unclear :)

BTW: Nice Project :)

### CODE REVIEW

**Comment by sebinside** [comment]
Thank you, looks very promising. I don't know much about Github CI, do I'll have to explicitly provide the secrets?

**Comment by dfuchss** [comment]
No. The CI uses an internal secret to access your repository. I think the only thing you have to do is merging :)

(Iff the CI does not start after that, you may have to look in the github action settings whether they are activated properly.)

**Comment by dfuchss** [comment]
So .. now I've added also a run config for PRs and a dependabot config for more recent versions of GH Actions.

**Comment by sebinside** [comment]
Thank you. Would it then be more clean to move all source files into an tex/-Folder an only have the CI-built source in the root?

**Comment by dfuchss** [comment]
I would use your current structure. Later you might change it. But for the current stage I think the structure is ok.

**Pull request merged**
